let Logger;
if(typeof window === 'undefined' || typeof process !== 'undefined' && process.versions?.node){
    Logger = require('log-ng');
	Logger({logLevel: 'warn', logFile: 'keygen.log'});
}else{
    Logger = require('log-ng').default;
}
const logger = new Logger('BigIntMath.js');
const smallIntThreshold = 2**53;

function flyweightCache(num){
	if(flyweightCache[num] !== undefined){
		logger.silly(`returning ${num}`);
		return flyweightCache[num];
	}
	if(num < smallIntThreshold){ // typically cached by the engine
		return BigInt(num);
	}
	logger.silly(`creating ${num}`);
	const biVal = BigInt(num);
	Object.defineProperty(flyweightCache, num, {
		get: function(){
			return biVal;
		}
	});
	return biVal;
}

const biMath = flyweightCache;
Object.defineProperties(biMath, {
	abs: {
		value: (n) => n < 0n ? -n : n
	},
	max: {
		value: (v, ...values) => values.reduce((acc, cur) => cur > acc ? cur : acc, v)
	},
	min: {
		value: (v, ...values) => values.reduce((acc, cur) => cur < acc ? cur : acc, v)
	},
	pow: {
		value: (base, exp, mod) => {
			if(mod === undefined){
				let result = 1n;
				while(exp > 0n){
					if(exp & 1n){
						result *= base;
					}
					base *= base;
					exp = exp / 2n;
				}
				return result;
			}
			let result = 1n;

			while(exp > 0n){
				if(exp % 2n === 1n){
					result = (result * base) % mod;
				}
				base = (base * base) % mod;
				exp = exp / 2n;
			}

			return result;
		}
	},
	random: {
		value: (min, max) => BigInt(Math.floor(Math.random() * Number(max - min + 1n))) + min
	},
	random_bytes: {
		value: (min, max) => {
			if(typeof min !== 'bigint'){
				min = BigInt(min);
			}
			if(typeof max !== 'bigint'){
				max = BigInt(max);
			}
			const range = max - min;
			const bytes = Math.ceil(range.toString(2).length / 8);
			const maxPossibleValue = (1n << (flyweightCache(bytes) * 8n)) - 1n;
			let randomBigInt = 0n;

			for(let i = 0; i < bytes; ++i){
				const randomByte = Math.floor(Math.random() * 256);
				randomBigInt = (randomBigInt << 8n) | BigInt(randomByte);
				logger.debug(`acc: ${randomBigInt}, generated byte ${randomByte}`);
			}

			randomBigInt = (randomBigInt * range) / maxPossibleValue;
			return randomBigInt + min;
		}
	},
	// generates a cryptographically secure random BigInt with given number of bits
	random_crypto: {
		value: (bits = 2n**(2n**20n-1n)) => {
			if(typeof bits !== 'bigint'){
				bits = BigInt(bits);
			}
			const bytes = Number((bits + 7n) / 8n);
			const randomBytes = new Uint8Array(bytes);
			crypto.getRandomValues(randomBytes);
			let randomBigInt = 0n;

			for(let i = 0; i < bytes; ++i){
				randomBigInt = (randomBigInt << 8n) | BigInt(randomBytes[i]);
			}

			const excessBits = (flyweightCache(bytes) * 8n) - bits;
			if(excessBits > 0n){
				randomBigInt = randomBigInt >> excessBits;
			}

			const topBitMask = 1n << (bits - 1n);
			randomBigInt = randomBigInt | topBitMask;

			return randomBigInt;
		}
	}
});

module.exports = biMath;
